set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN M14 [get_ports clk]
set_property PACKAGE_PIN R17 [get_ports D]
set_property PACKAGE_PIN T14 [get_ports pl]
set_property PACKAGE_PIN T11 [get_ports reset]
set_property PACKAGE_PIN Y19 [get_ports Q]
set_property IOSTANDARD LVCMOS33 [get_ports D]
set_property IOSTANDARD LVCMOS33 [get_ports pl]
set_property IOSTANDARD LVCMOS33 [get_ports Q]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
